//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestesAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class API_TESTESEntities : DbContext
    {
        public API_TESTESEntities()
            : base("name=API_TESTESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOY> BOY { get; set; }
        public virtual DbSet<TOY> TOY { get; set; }
        public virtual DbSet<TP_TOY> TP_TOY { get; set; }
        public virtual DbSet<BOY_TOY> BOY_TOY { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
